### ISSUE TITLE
Transcription tab should be scrollable 

### ISSUE THREAD

**Issue by chobberoni** [daily-demos/ai-meeting-assistant#12]
## Feedback
1. After several minutes in a live call it becomes evident that the transcript tab becomes mildly unusable given the text does not scroll. You only get the first 30 seconds of any call & beyond that the transcript could be cleaned up and chunked together. This would reduce the need to show the full diarization in such a small surface area.
2. When folks join the call after the call has been running for 30 seconds or a couple of minutes they do not have access to the transcript that happened before they joined. This leads to inaccuracies when asking the AI summarizer what happened or was said in this call. It does not have the right context window to query against.

## Requests
1. Enable the transcript window to be scrollable
2. Chunk up the transcript to make it more readable -- however, the tradeoff is showing the diarization...
3. Allow folks who have joined late to see the transcript from before they joined -- this may require caching/storing the transcript

**Comment by lazeratops** [comment]
Going to assign this one to @Regaddi for the scrolling

I think number 2 might not be accurate. From what I understand the client simply sends a custom query to the server to clean up the transcript, and the server has the full context (@Regaddi can confirm whether that's correct). What is the output issue you are seeing that leads you to believe the full context is not available?

**Comment by lazeratops** [comment]
Closing as fixed for the scrollable transcription. Point 2 can be a separate issue; some clarification needed here as mentioned in above comment.
